"""Extract PDF text to Markdown, with PNG page links for image-only / sparse pages.

Intended workflow:
  1. python scripts/pdf_to_png.py <folder>     # visual pages (gitignored)
  2. python scripts/pdf_to_md.py <folder>      # text index (commit-friendly)
  3. Read MD first; open linked PNG only when figures / broken text need eyes

Requires: pip install pymupdf
Optional OCR: Tesseract + Japanese traineddata, then pass --ocr

Folder mode:
  python scripts/pdf_to_md.py docs/research_notes/google_doc
  -> docs/research_notes/google_doc/MD/<pdf_stem>/content.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


SPARSE_TEXT_CHARS = 40


def require_fitz():
    try:
        import fitz  # pymupdf
    except ImportError as exc:
        raise SystemExit(
            "pymupdf is required. Install with: pip install pymupdf"
        ) from exc
    return fitz


def collect_pdfs(paths: list[Path]) -> list[tuple[Path, Path]]:
    """Return (pdf_path, md_root) pairs. md_root holds <pdf_stem>/content.md."""
    jobs: list[tuple[Path, Path]] = []
    for raw in paths:
        path = raw.resolve()
        if path.is_dir():
            pdfs = sorted(path.glob("*.pdf")) + sorted(path.glob("*.PDF"))
            seen: set[Path] = set()
            unique: list[Path] = []
            for pdf in pdfs:
                key = pdf.resolve()
                if key in seen:
                    continue
                seen.add(key)
                unique.append(pdf)
            if not unique:
                print(f"warning: no PDFs in {path}", file=sys.stderr)
                continue
            md_root = path / "MD"
            for pdf in unique:
                jobs.append((pdf, md_root))
        elif path.is_file() and path.suffix.lower() == ".pdf":
            jobs.append((path, path.parent / "MD"))
        elif path.exists():
            raise SystemExit(f"error: not a PDF or directory: {path}")
        else:
            raise SystemExit(f"error: not found: {path}")
    return jobs


def page_png_name(page_index: int, page_count: int) -> str:
    width = max(3, len(str(page_count)))
    return f"page_{page_index:0{width}d}.png"


def extract_page_text(page, *, ocr: bool, ocr_lang: str, ocr_dpi: int) -> tuple[str, str]:
    """Return (text, method) where method is 'native' | 'ocr' | 'empty'."""
    native = page.get_text("text").strip()
    if native:
        return native, "native"
    if not ocr:
        return "", "empty"
    try:
        tp = page.get_textpage_ocr(dpi=ocr_dpi, language=ocr_lang, full=True)
        ocr_text = page.get_text("text", textpage=tp).strip()
    except Exception as exc:  # noqa: BLE001 — surface OCR setup issues per page
        return f"[OCR failed: {exc}]", "ocr"
    if ocr_text:
        return ocr_text, "ocr"
    return "", "empty"


def md_escape_heading(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip() or "(untitled)"


def build_content_md(
    pdf_path: Path,
    pages: list[dict],
    *,
    link_png: str,
) -> str:
    stem = pdf_path.stem
    sparse_or_empty = sum(
        1 for page in pages if len(page["text"]) < SPARSE_TEXT_CHARS
    )
    lines: list[str] = [
        f"# {md_escape_heading(stem)}",
        "",
        f"- Source PDF: `{pdf_path.name}`",
        f"- Pages: {len(pages)}",
        f"- Sparse/empty pages: {sparse_or_empty}/{len(pages)}",
        f"- Companion PNG: `../../PNG/{stem}/`",
        "- Generated by `scripts/pdf_to_md.py`",
        "",
        "Read this file first. Open linked PNG pages when figures are missing "
        "or extracted text looks broken / empty.",
        "",
    ]

    for page in pages:
        text = page["text"]
        method = page["method"]
        n_chars = len(text)
        is_sparse = n_chars < SPARSE_TEXT_CHARS
        png_rel = f"../../PNG/{stem}/{page['png_name']}"
        show_png = link_png == "always" or (
            link_png == "sparse" and is_sparse
        )

        lines.append(f"## Page {page['index']}")
        lines.append("")
        lines.append(
            f"_extraction: {method}, chars={n_chars}"
            + (" (sparse/empty — prefer PNG)" if is_sparse else "")
            + "_"
        )
        lines.append("")
        if show_png:
            lines.append(f"[PNG page]({png_rel})")
            lines.append("")
        if text:
            lines.append(text)
            lines.append("")
        else:
            lines.append("*(no extractable text on this page)*")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def convert_pdf(
    pdf_path: Path,
    md_root: Path,
    *,
    ocr: bool,
    ocr_lang: str,
    ocr_dpi: int,
    link_png: str,
) -> Path:
    fitz = require_fitz()
    out_dir = md_root / pdf_path.stem
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "content.md"

    pages: list[dict] = []
    with fitz.open(pdf_path) as doc:
        for i, page in enumerate(doc, start=1):
            text, method = extract_page_text(
                page, ocr=ocr, ocr_lang=ocr_lang, ocr_dpi=ocr_dpi
            )
            pages.append(
                {
                    "index": i,
                    "text": text,
                    "method": method,
                    "png_name": page_png_name(i, doc.page_count),
                }
            )
            print(
                f"  page {i}/{doc.page_count}: method={method}, "
                f"chars={len(text)}"
            )

    out_path.write_text(
        build_content_md(pdf_path, pages, link_png=link_png),
        encoding="utf-8",
    )
    return out_path


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Extract PDF text to Markdown under <folder>/MD/<pdf_stem>/content.md. "
            "Links to PNG companions for sparse/image-only pages."
        )
    )
    parser.add_argument(
        "inputs",
        nargs="+",
        type=Path,
        help="Input folder(s) and/or PDF file(s)",
    )
    parser.add_argument(
        "--ocr",
        action="store_true",
        help="OCR pages with no native text (needs Tesseract + lang data)",
    )
    parser.add_argument(
        "--ocr-lang",
        default="jpn+eng",
        help="Tesseract language(s) for --ocr (default: jpn+eng)",
    )
    parser.add_argument(
        "--ocr-dpi",
        type=int,
        default=300,
        help="OCR render DPI (default: 300)",
    )
    parser.add_argument(
        "--link-png",
        choices=("sparse", "always", "never"),
        default="sparse",
        help="When to add PNG links (default: sparse)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    jobs = collect_pdfs(args.inputs)
    if not jobs:
        print("error: nothing to convert", file=sys.stderr)
        return 1

    for pdf, md_root in jobs:
        print(f"{pdf.name} -> {md_root / pdf.stem / 'content.md'}")
        out = convert_pdf(
            pdf,
            md_root,
            ocr=args.ocr,
            ocr_lang=args.ocr_lang,
            ocr_dpi=args.ocr_dpi,
            link_png=args.link_png,
        )
        print(f"  wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
